{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "yeti-management.fullname" . -}}
{{- $servicePort := .Values.service.servicePort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "yeti-management.fullname" . }}
  labels:
{{ include "management_labels" . | indent 4}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
