apiVersion: v1
kind: Secret
metadata:
  name: {{ template "yeti-management.fullname" . }}
  labels:
{{ include "management_labels" . | indent 4}}
type: Opaque
data:
  #Routing
  routing_master_db_name: {{ .Values.secret.routingMasterDbName | b64enc | quote }}
  routing_master_db_user: {{ .Values.secret.routingMasterDbUser | b64enc | quote }}
  routing_master_db_pass: {{ .Values.secret.routingMasterDbPass | b64enc | quote }}
  routing_slave_db_name: {{ .Values.secret.routingSlaveDbName | b64enc | quote }}
  routing_slave_db_user: {{ .Values.secret.routingSlaveDbUser | b64enc | quote }}
  routing_slave_db_pass: {{ .Values.secret.routingSlaveDbPass | b64enc | quote }}
  #CDR
  cdr_master_db_name: {{ .Values.secret.cdrMasterDbName | b64enc | quote }}
  cdr_master_db_user: {{ .Values.secret.cdrMasterDbUser | b64enc | quote }}
  cdr_master_db_pass: {{ .Values.secret.cdrMasterDbPass | b64enc | quote }}
  cdr_slave_db_name: {{ .Values.secret.cdrSlaveDbName | b64enc | quote }}
  cdr_slave_db_user: {{ .Values.secret.cdrSlaveDbUser | b64enc | quote }}
  cdr_slave_db_pass: {{ .Values.secret.cdrSlaveDbPass | b64enc | quote }}
